version: "3.8"

networks:
  default:
    name: typingrealm
    external: true

services:
  kartman-web:
    image: ghcr.io/ewancoder/kartman-web:main
    container_name: kartman-web
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  kartman-api:
    image: ghcr.io/ewancoder/kartman-api:main
    container_name: kartman-api
    volumes:
      - /data/kartman/cache:/app/cache
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - /data/kartman/secrets.env

  kartman-postgres:
    image: postgres
    container_name: kartman-postgres
    ports:
      - 10232:5432 # Port shouldn't be exposed in production.
    volumes:
      - /data/kartman/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - /data/kartman/secrets.env
