version: "3.8"

networks:
  default:
    name: typingrealm

services:
  kartman-ui:
    image: ${DOCKER_REGISTRY-}kartman-ui
    container_name: kartman-ui
    build:
      context: frontend/.
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  kartman-api:
    image: ${DOCKER_REGISTRY-}kartman-api
    container_name: kartman-api
    build:
      context: backend/.
      dockerfile: KartMan.Api/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - secrets.env

  kartman-postgres:
    image: postgres
    container_name: kartman-postgres
    ports:
      - 10232:5432 # Port shouldn't be exposed in production.
    volumes:
      - ./infrastructure-data/prod/kartman/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - secrets.env
