name: Deploy

on:
  push:
    branches:
      - 'main'
      - 'develop'

env:
  REGISTRY: ghcr.io

jobs:
  build-api:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/ewancoder/kartman-api

    - name: Build and push API Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ./backend
        file: backend/KartMan.Api/Dockerfile-production
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  build-web-ui:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/ewancoder/kartman-web

    - name: Build and push Production API Docker image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ./frontend
        file: frontend/Dockerfile-production
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Development API Docker image
      if: github.ref == 'refs/heads/develop'
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ./frontend
        file: frontend/Dockerfile-development
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build-api, build-web-ui]

    permissions:
      contents: read

    steps:
    - name: Deploy to DO
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSWORD }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          curl https://raw.githubusercontent.com/ewancoder/kartman/main/docker-compose-production.yml > /tmp/kartman-docker-compose.yml
          docker compose -f /tmp/kartman-docker-compose.yml pull
          docker compose -f /tmp/kartman-docker-compose.yml up -d

  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: [build-api, build-web-ui]

    permissions:
      contents: read

    steps:
    - name: Deploy DEV to DO
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSWORD }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          curl https://raw.githubusercontent.com/ewancoder/kartman/develop/docker-compose-development.yml > /tmp/dev-kartman-docker-compose.yml
          docker compose -f /tmp/dev-kartman-docker-compose.yml pull
          docker compose -f /tmp/dev-kartman-docker-compose.yml up -d
